services:
  - mongodb
  - postgresql

sudo: required
dist: trusty

language: node_js

node_js:
  - '10'
  - '11'

before_install:
  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - git fetch -a
  # - git fetch origin master
  # - sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
  # - npm cache clean --force
  # - rm -rf node_modules/

install:
  - npm run setup:build
  - npm install -g wait-on
  - ls ~/.cache
  - cypress install

before_script:
  - psql -c 'create database strapi_test;' -U postgres

script:
  # default unit test
  - npm run test:unit
  # e2e trests
  - node test/createTestApp.js --dbclient=postgres --dbhost=localhost --dbport=5432 --dbname=strapi_test --dbusername=postgres --dbpassword=
  - node test/startTestApp.js & wait-on http://localhost:1337
  - npm run test:e2e
  # cypress tests
  - node test/createTestApp.js --dbclient=mongo --dbhost=localhost --dbport=27017 --dbname=strapi_test --dbusername= --dbpassword=
  - node test/startTestApp.js & wait-on http://localhost:1337
  - node test/cypress.js
  # lint and doc
  - npm run lint
  - npm run doc

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
